### ISSUE TITLE
生成PDF时出现错误

### ISSUE THREAD

**Issue by xukuang** [yihui/bookdown-chinese#10]
这个目录下载到本地后，Build Book选择bookdown::gitbook能正常运行，但是选择bookdown::pdf_book总是产生如下错误：
Use of uninitialized value in concatenation (.) or string at C:\ProgramFiles\CTEX\MiKTeX\scripts\latexmk\perl\latexmk.pl line 830.
! Undefined control sequence.
<argument> \XeTeXLinkMargin 

Error: Failed to compile bookdown.tex. See bookdown.log for more info.
In addition: Warning messages:
1: running command '"C:\PROGRA\~4\CTEX\MiKTeX\miktex\bin\latexmk.exe" -v' had status 1 
2: The LaTeX package latexmk was not correctly installed. 
3: running command '"C:\PROGRA~4\CTEX\MiKTeX\miktex\bin\latexmk.exe" -v' had status 1 
4: running command '"xelatex" -halt-on-error -interaction=batchmode "bookdown.tex"' had status 1 
Execution halted

Exited with status 1.

请问这是我的CTEX没有安装好，还是其它问题？我猜想应该不是软件版本的问题，因为下载https://github.com/rstudio/bookdown-demo 这个英文目录时，能够正常生成pdf文件。所有测试都是在windows系统下完成的。

**Comment by yihui** [comment]
参见 #7
