### ISSUE TITLE
怎样设置 coding.net repo

### ISSUE THREAD

**Issue by sierxue** [yihui/bookdown-chinese#11]
在index.rmd里，如果我想设置其它repo，比如coding.net上的repo，我应该怎么设置？

**Comment by yihui** [comment]
你想达到的目的是什么？

**Comment by sierxue** [comment]
因为国内访问 github 较慢，我的Rmd文件是放在 coding.net 上的 repo 里。我希望合作者点击左上编辑按钮时，访问相应的 repo. 比如访问你的页面 https://bookdown.org/yihui/blogdown/a-quick-example.html 时，点击编辑按钮，进入coding.net 上的 repo.

**Comment by yihui** [comment]
我不熟悉 coding.net 主要是它得有跟 Github 类似的功能，即：`https://github.com/用户名/库名/edit/分支名/文件名` 这个链接可以让任何人编辑文档。例如：

https://github.com/yihui/bookdown-chinese/edit/master/index.Rmd

详情参见 edit 选项：https://bookdown.org/yihui/bookdown/html.html#gitbook-style bookdown 所做的事情是把你提供的链接中的 `%s` 替换为文件名。

如果 coding.net 做不到用这样的链接编辑文件，那臣妾也做不到让你有一个称心的编辑按钮。
