### ISSUE TITLE
在 CTeX 2.9.2 下 building pdf_book 时遇到的麻烦

### ISSUE THREAD

**Issue by haopen** [yihui/bookdown-chinese#12]
麻烦 1（已解决）. `Latexmk: Bad options specified`

Building book 为 pdf 的时候，在 Building 窗口中会显示如下的错误：

```
Latexmk: -latexoption bad option
Latexmk: -interaction bad option
Latexmk: -pdflatex bad option

Latexmk: Bad options specified
Use
   latexmk -help
to get usage information
����: Failed to compile bookdown.tex.
```

**解决方法**：到 [CTAN](https://www.ctan.org/pkg/latexmk/) 下载 `latexmk` 的压缩包，解压后复制其中的 `latexmk.pl` 到 `C:\CTEX\MiKTeX\scripts\latexmk\perl`，覆盖旧版本的 `latexmk.pl`；

**警告**：不要按照 `INSTALL` 中说的那样，将 `latexmk.bat` 复制到 `C:\CTEX\MiKTeX\miktex\bin`，用于替代其中的 `latexmk.exe`，否则仍然会出现类似上面的错误。

**原因分析**：

1. CTeX  2.9.2.164 中 `latexmk.pl` 版本为 `4.30a`，对应的时间为 2011 年，因此 `bookdown` 调用这个版本中的接口程序 `C:\CTEX\MiKTeX\miktex\bin\latexmk.exe` 时，就会抛出上面的错误；
2. MikTeX 中通过 `latexmk.bat` 或者 `latexmk.exe` 调用主程序 `latexmk.pl`，这一点和 Linux 或其它 OS 上可能有所区别， RStudio 中也是按这一流程完成调用的。然而，如果用新版中的 `latexmk.bat`，最终传递给 `latexmk.pl` 的参数是不完整的，大概呈如下的形式：

```
1. C:\CTEX\MiKTeX\miktex\bin\latexmk.bat" -pdf -latexoption=-halt-on-error -interaction=batchmode -pdflatex="xelatex" "bookdown.tex"

2. perl -S latexmk.pl -pdf -latexoption -halt-on-error -interaction batchmode -pdflatex "xelatex"
```

也就是说，`latexmk.bat` 这时候只是将 `value` 部分传递给了 `latexmk.pl`，而 `key` 部分却丢失了。

庆幸的是，CTEX 2.9.2.164 中的 `latexmk.exe` 却可以将正确的参数全部传递给 `latexmk.pl`，因此不可以按照 `INSTALL` 中说的那样将 `latexmk.bat` 作为调用 `latexmk.pl` 的接口。

------

麻烦 2（已解决）：参见 #7 ，这种做法最直接有效。

------

麻烦 3（未解决）：

从 [`render.R`](https://github.com/rstudio/rmarkdown/blob/b6e3f39f731b28af5ff1823c0de8714d8fb78df7/R/render.R) 的源代码看，`bookdown` 应该是直接指定调用 latex 引擎的方式为 `latexmk`，我知道这货很强大，很不错，很。。。

可是现在要想让 latexmk 按照设想的方式工作可能需要比较高的成本，我就想问问老大可不可以在 Pandoc 生成 tex 文件之后，自定义编译文档的脚本文件，比如通过自己写的 `make.bat` 什么的来完成编译，而不是通过 `latexmk` 来完成？

**Comment by yihui** [comment]
其实我一直都想开放 rmarkdown 中的编译方式，把那部分代码抽离出来，让用户可以自定义，只不过我还没有时间顾得上这事。

**Comment by haopen** [comment]
为了个配置文件 `latexmkrc` 去了解 perl，实在做不到啊，我先发个 email 给作者碰碰运气，哈哈。

**Comment by haopen** [comment]
联系 `latexmkrc` 的作者后得到了一个折中的解决方案，大概意思是我可以以这样的方式：

```txt
$bibtex = 'mybibtex %R';
$makeindex = 'mymakeindex %R';
```

自定义编译的脚本文件，其中 `mybibtex.bat` 和 `mymakeindex.bat` 中可以包含自定义处理过程。

作者还提到文档中的 "FORMAT OF COMMAND SPECIFICATIONS" 部分有更好的解决方案，当然前提是了解  perl。

**Comment by yihui** [comment]
现在你可以用 https://yihui.name/tinytex/ 了。再也不用操心与 R Markdown 有关的 LaTeX 问题。

**Comment by haopen** [comment]
熟悉 RMarkdown 的工作流程后，直接使用 XeLaTeX 编译文档的场景已经越来越少，这次自己做 beamer presentation 模板的时候遇到了不少问题，有好几个和 CTeX 提供的工具和宏包的版本太旧有关的小麻烦。

关注 tinytex 有好一段时间，非常棒的工作，等过完年后找时间尽快熟悉下，将工作转移过来。

**Comment by joe-zxh** [comment]
👍解决了我的问题
