### ISSUE TITLE
版权问题

### ISSUE THREAD

**Issue by bubifengyun** [yihui/bookdown-chinese#13]
刚刚，非常感谢你在 https://github.com/yihui/r-ninja/issues/24 这里提供的解决方案。现在我可以成功编译出有汉字的 PDF 文件了。我打算以这个为模板，改动一下，写点东西出来，本文有啥权限限制没，谢谢。

**Comment by bubifengyun** [comment]
不好意思，没有仔细看，有版权说明。打扰了。

**Comment by yihui** [comment]
没事。我对版权的要求并不高，我的底线是只要你说清楚哪些是你自己的工作、哪些是我的工作就好了。我不想冒领别人的功劳，也不想别人冒领我的功劳。就是这样。
