### ISSUE TITLE
生成pdf时，图片里的中文不显示

### ISSUE THREAD

**Issue by Pomelocake** [yihui/bookdown-chinese#14]
你好！最近刚在学习bookdown，软件和包又重装了都是最新版的，有几个问题想请教一下。

1.改了rmd文件后，生成的pdf，图片里的中文都没有显示，表格是没有问题的，其他格式（gitbook、epub、word）也都没有问题
![image](https://user-images.githubusercontent.com/32633431/31581032-b614d1b8-b192-11e7-8687-320275698d60.png)
还有这个(#fig:block3.2)如何让它不显示啊？

2.生成的pdf，正文前面的表格和插图这两部分怎么删掉？

3.生成的word里面不会自动添加"第X章"吗？

**Comment by yihui** [comment]
1. R 图形中的中文字符永远是个麻烦。我长话短说一个可能的解决方案：`install.packages("showtext")` 然后用代码段选项 `fig.showtext = TRUE`。

    代码段标签中只能用有限的字符集：https://bookdown.org/yihui/bookdown/figures.html `block3.2` 中的点不在这个字符集内。

1. https://github.com/yihui/bookdown-chinese/blame/master/index.Rmd#L10-L11

1. 不会。
