### ISSUE TITLE
`block2` 可以用在普通的非 `bookdown` 的 Rmd 文档中吗？

### ISSUE THREAD

**Issue by haopen** [yihui/bookdown-chinese#20]
R, RStudio 以及 bookdown 都是最新版的，系统是 Win7，用 CTeX 的 XeLaTeX 编译文档。

尝试在普通的 Rmd 文档中使用 `block2` 时，生成的临时 `.tex` 文档中并不会包含任何与 `block2` 代码块对应的内容(也不包含相应的 LaTeX 环境)，所以想请教下是否可以直接在普通的 Rmd 文档中使用 `block2`？

谢谢。

**Comment by yihui** [comment]
可以。block2 是 knitr 中定义的，而不是 bookdown 定义的，bookdown 只是基于它做了一些定理、证明环境的扩展。

**Comment by haopen** [comment]
谢谢 yihui，原来是新建 beamer_presentation 时，`knitr::opts_chunk$set(echo = FALSE)` 里面 `echo` 的取值默认是 `FALSE` 造成的，改成 `TRUE` 结果就正确了：

```tex
\begin{foo}[bar]
test block
\end{foo}

\BeginKnitrBlock{foo}\iffalse{-91-98-97-114-93-}\fi{}

test block2

\EndKnitrBlock{foo}
```

看到上面的一串数字才意识到书里面为什么说要去读源代码，坑真多啊。
