### ISSUE TITLE
~后面的文字诡异变成了textsubscript格式

### ISSUE THREAD

**Issue by taiyun** [yihui/bookdown-chinese#27]
照猫画虎，在牛刀小试后面加如下段落：

```
每年研发经费中，约20%~30%用于研究和创新，70%用于产品开发。很早以前我们就将销售收入的10%以上用于研发经费。未来几年，每年的研发经费会逐步提升到100~200亿美元。
```

生成的pdf中，20%后面--200亿美元前面的文字变的很小。看了下，两个`~`中间的文字变成了`\textsubscript`，生成的tex如下：

```
每年研发经费中，约20\%\textsubscript{30\%用于研究和创新，70\%用于产品开发。很早以前我们就将销售收入的10\%以上用于研发经费。未来几年，每年的研发经费会逐步提升到100}200亿美元。
```

何解？

**Comment by yihui** [comment]
两个波浪符在 Pandoc Markdown 语法中表示下标：https://bookdown.org/yihui/bookdown/markdown-syntax.html

若需要原始波浪符，前面加个反斜杠即可：`\~`

**Comment by taiyun** [comment]
明白了。

另一个问题是原文有一些`[1]` `[2]`，需要直接显示。但在生成的tex中，变成了`\protect\hyperlink{section-1}{1}`之类的，得到了意外的交叉引用。 这个如何解决呢？

**Comment by yihui** [comment]
凡是需要避免特殊语法含义的字符，前面都加反斜杠。

**Comment by taiyun** [comment]
了解，多谢！
