### ISSUE TITLE
关于模板的几个问题?

### ISSUE THREAD

**Issue by xie186** [yihui/bookdown-chinese#3]
1）在使用本模板的时候，会自动生成表格和插图列表。请问如何去除这两项？
2）在生成PDF的时候，为什么cover figure 不出现在首页上？
3）如何是pdf文件不出现左上或右上的页码？或者如何删除下方的页码?
谢谢！

**Comment by yihui** [comment]
1. index.Rmd 里 lot/lof 选项去掉，或设置成 false；
1. 不造。
1. 这是 LaTeX 问题，需要自行放狗搜。

不谢！
