### ISSUE TITLE
htmlTable 在book-chinese中不work

### ISSUE THREAD

**Issue by xie186** [yihui/bookdown-chinese#4]
我想用htmlTable生成一个表格。
结果如下只给出了下面的结果：
![image](https://cloud.githubusercontent.com/assets/20909751/22131389/1a67829a-de81-11e6-93d8-7b557ed59b0e.png)
下面是我添加的内容：
当然我在开头和末尾添加了```

```{r}
 library(htmlTable)
# A simple output
output <- matrix(1:4,
                 ncol=2,
                 dimnames = list(list("Row 1", "Row 2"),
                                 list("Column 1", "Column 2")))
htmlTable(output)
```

**Comment by yihui** [comment]
我没用过 htmlTable 包，不熟，这个问题不属于 bookdown 范畴，建议在 StackOverflow 提问。
