### ISSUE TITLE
Is it possible that I can insert an picture via htmlTable? 

### ISSUE THREAD

**Issue by xie186** [yihui/bookdown-chinese#5]
For example, I need to generate a table like this:
In the top right, I'd like to insert a photo. Is it possible that I can do this using htmlTable. I saw your [post](http://stackoverflow.com/questions/25106481/add-an-image-to-a-table-like-output-in-r).  But the problem is the table I'd like to generate needs row span. 

Can you help me on this? Thanks. 

![image](https://cloud.githubusercontent.com/assets/20909751/22131616/86b9475c-de82-11e6-83a8-76e7d39bca04.png)

**Comment by yihui** [comment]
这事超出了我的范围。你得问具体的第三方包的作者。
